# Generated by Django 4.2.7 on 2024-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rate",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
