"""
Django settings for WebsitePorject project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Dataset')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-o%ykroim##iooqyisphhr8dan3kvx17=hp7!+zq*^dgb8yex+f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #
# Debug
INTERNAL_IPS = [
    '127.0.0.1', # debug ip
]

ALLOWED_HOSTS = ['*']

# Session setting
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True # Prevent JavaScript from accessing session cookies
SESSION_COOKIE_AGE = 1200 # Setting a session timeout (20 min)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# CSP
CSP_SCRIPT_SRC = ("'self'", 'https://s3.pstatp.com', "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", "data:")
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com", "'unsafe-inline'")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")
CSP_FORM_ACTION = ("'self'",) # form
CSP_FRAME_ANCESTORS = ("'self'",)

# CSRF
CSRF_COOKIE_HTTPONLY = True


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'debug_toolbar', # debug tools
    'polls',
    'accounts',
    'cart',
    'customers',
    'merchants',
    'orders',
    'payment',
    'products',
    'store',
    'recommendation',
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # debug toolbar
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    'csp.middleware.CSPMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "WebsitePorject.urls"

# set where can find the template
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "WebsitePorject.wsgi.application"

# Database - mysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'onlinefooddelivery',
        'USER': 'root',
        'PASSWORD': 'halo1234',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
        'MYSQL': {
            'driver': 'pymysql',
            'charset': 'utf8mb4',
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# set the static path
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    ("css", os.path.join(STATIC_ROOT, 'css')),
    ("image", os.path.join(STATIC_ROOT, 'image')),
    ("js", os.path.join(STATIC_ROOT, 'js')),
    ("json", os.path.join(STATIC_ROOT, 'json')),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
