# Generated by Django 4.2.7 on 2024-03-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("accounts", "0001_initial"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favored_by",
                to="merchants.product",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="accounts.customer",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="merchants.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favitem", unique_together={("customer", "product")},
        ),
    ]
