# Generated by Django 4.2.7 on 2024-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address_city_address_detail_address_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="total_rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
