# Generated by Django 4.2.7 on 2024-04-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_shop_total_rating"),
    ]

    operations = [
        migrations.RemoveField(model_name="shoppingcart", name="quantity",),
    ]
