# Generated by Django 4.2.7 on 2024-04-24 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_shoppingcart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
            preserve_default=False,
        ),
    ]
