# Generated by Django 4.2.7 on 2024-04-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_shoppingcart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="username",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
