# Generated by Django 4.2.7 on 2024-03-22 14:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address_city_address_detail_address_district_and_more"),
        ("merchants", "0001_initial"),
        ("orders", "0002_order_address_line_order_delivery_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="product",),
        migrations.RemoveField(model_name="order", name="product_price",),
        migrations.RemoveField(model_name="order", name="quantity",),
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.shop",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderitems",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="merchants.product",
                    ),
                ),
            ],
        ),
    ]
