# Generated by Django 4.2.7 on 2024-04-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_iscomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line",
            field=models.CharField(default="", max_length=255),
        ),
    ]
