# Generated by Django 4.2.7 on 2024-04-24 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_address_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="sale_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
